spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kistadb}
    username: ${DB_USERNAME:kista}
    password: ${DB_PASSWORD:kista}

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
